### ISSUE TITLE
.hidden-tab layer error

### ISSUE THREAD

**Issue by ZhengLinLei** [ZhengLinLei/paste-code#30]
Two task:

* First: In safari the hover doesn't work properly. Check this link [Stackoverflow](https://stackoverflow.com/questions/35187970/css-hover-not-working-on-ios-safari-and-chrome)

* Second: When you open terminal. It colapse the layer priority in some devices. Add higher layer number to `.hidden-tab` or reorder the layers correctly to avoid problems in the future. Also you can add more padding to `.hidden-tab`, currently it is defined as `padding-left: 10px;`

**Comment by ZhengLinLei** [comment]
Extra feature: Make the .hidden-tab with bottom relative to terminal section. If we resize the terminal , the div.hidden-tab must move relativaly terminal position.

<img width="1680" alt="Screenshot 2023-11-23 at 11 50 34" src="https://github.com/ZhengLinLei/paste-code/assets/77938581/16c8bd34-d60a-4a0c-8255-819acc17b4ee">

**Comment by tostadanevera** [comment]
massa feina
